In [2]:
#파일 불러오기 
words = open('names.txt','r').read().splitlines()
words[:10]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [2]:
min(len(w)for w in words)

2

In [3]:
len(words)

32033

In [4]:
#가장 짧은 단어
min(len(w)for w in words)

2

In [5]:
#가장 긴 단어
max (len (w)for w in words)

15

## Counting bigrams in a python dictionary

In [3]:
b = {}
for w in words[:3]:  #슬라이싱 연사자 사용함
    chs=['<S>'] + list(w) + ['<E>'] #단어의 시작과 끝을 알기 위해 
    for ch1 , ch2 in zip(chs,chs[1:]):
        bigram = (ch1,ch2)
        b[bigram] = b.get(bigram,0) + 1
        print(ch1,ch2)

<S> e
e m
m m
m a
a <E>
<S> o
o l
l i
i v
v i
i a
a <E>
<S> a
a v
v a
a <E>


In [7]:
b #여기서 3번 나온 것은 a<E>가 3번 발생했다는 것이다. 즉 위를 보면 a <E>가 3번 발생함 

{('<S>', 'e'): 1,
 ('e', 'm'): 1,
 ('m', 'm'): 1,
 ('m', 'a'): 1,
 ('a', '<E>'): 3,
 ('<S>', 'o'): 1,
 ('o', 'l'): 1,
 ('l', 'i'): 1,
 ('i', 'v'): 1,
 ('v', 'i'): 1,
 ('i', 'a'): 1,
 ('<S>', 'a'): 1,
 ('a', 'v'): 1,
 ('v', 'a'): 1}

In [4]:
#데이터 전체 bigram화 시켜보기
b = {}
for w in words:  #슬라이싱 연사자 사용함
    chs=['<S>'] + list(w) + ['<E>'] #단어의 시작과 끝을 알기 위해 
    for ch1 , ch2 in zip(chs,chs[1:]):
        bigram = (ch1,ch2)
        b[bigram] = b.get(bigram,0) + 1

In [5]:
sorted(b.items() ,key = lambda kv: kv[1]) #items라는 메소드는 dictionary형태로 반환함 


[(('q', 'r'), 1),
 (('d', 'z'), 1),
 (('p', 'j'), 1),
 (('q', 'l'), 1),
 (('p', 'f'), 1),
 (('q', 'e'), 1),
 (('b', 'c'), 1),
 (('c', 'd'), 1),
 (('m', 'f'), 1),
 (('p', 'n'), 1),
 (('w', 'b'), 1),
 (('p', 'c'), 1),
 (('h', 'p'), 1),
 (('f', 'h'), 1),
 (('b', 'j'), 1),
 (('f', 'g'), 1),
 (('z', 'g'), 1),
 (('c', 'p'), 1),
 (('p', 'k'), 1),
 (('p', 'm'), 1),
 (('x', 'n'), 1),
 (('s', 'q'), 1),
 (('k', 'f'), 1),
 (('m', 'k'), 1),
 (('x', 'h'), 1),
 (('g', 'f'), 1),
 (('v', 'b'), 1),
 (('j', 'p'), 1),
 (('g', 'z'), 1),
 (('v', 'd'), 1),
 (('d', 'b'), 1),
 (('v', 'h'), 1),
 (('h', 'h'), 1),
 (('g', 'v'), 1),
 (('d', 'q'), 1),
 (('x', 'b'), 1),
 (('w', 'z'), 1),
 (('h', 'q'), 1),
 (('j', 'b'), 1),
 (('x', 'm'), 1),
 (('w', 'g'), 1),
 (('t', 'b'), 1),
 (('z', 'x'), 1),
 (('p', 'b'), 2),
 (('t', 'g'), 2),
 (('q', 's'), 2),
 (('t', 'x'), 2),
 (('f', 'k'), 2),
 (('b', 't'), 2),
 (('j', 'n'), 2),
 (('k', 'c'), 2),
 (('z', 'k'), 2),
 (('s', 'j'), 2),
 (('s', 'f'), 2),
 (('z', 'j'), 2),
 (('n', 'q

## Counting bigrams in a 2D torch tensor ("training the model")

In [6]:
import torch


In [7]:
#Tensor dPtl 
a = torch.zeros((3,5))
a[ 1,3]  =1 #특정 행렬 바꾸기 
a

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0.]])

In [8]:
N = torch.zeros((28,28),dtype = torch.int32)

In [9]:
chars = sorted(set(''. join(words)))
stoi = {s:i for i,s in enumerate (chars)}
stoi['<S>'] =26
stoi['<E>'] = 27
stoi

{'a': 0,
 'b': 1,
 'c': 2,
 'd': 3,
 'e': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25,
 '<S>': 26,
 '<E>': 27}

In [16]:

for w in words:  #슬라이싱 연사자 사용함
    chs=['<S>'] + list(w) + ['<E>'] #단어의 시작과 끝을 알기 위해 
    for ch1 , ch2 in zip(chs,chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        N[ix1,ix2] +=1

In [17]:
N #시각화 해야함 보기에 이상함 

tensor([[ 1112,  1082,   940,  2084,  1384,   268,   336,  4664,  3300,   350,
          1136,  5056,  3268, 10876,   126,   164,   120,  6528,  2236,  1374,
           762,  1668,   322,   364,  4100,   870,     0, 13280],
        [  642,    76,     2,   130,  1310,     0,     0,    82,   434,     2,
             0,   206,     0,     8,   210,     0,     0,  1684,    16,     4,
            90,     0,     0,     0,   166,     0,     0,   228],
        [ 1630,     0,    84,     2,  1102,     0,     4,  1328,   542,     6,
           632,   232,     0,     0,   760,     2,    22,   152,    10,    70,
            70,     0,     0,     6,   208,     8,     0,   194],
        [ 2606,     2,     6,   298,  2566,    10,    50,   236,  1348,    18,
             6,   120,    60,    62,   756,     0,     2,   848,    58,     8,
           184,    34,    46,     0,   634,     2,     0,  1032],
        [ 1358,   242,   306,   768,  2542,   164,   250,   304,  1636,   110,
           356,  6496,  1

In [9]:
import matplotlib.pyplot as plt
# %matplotlib inline
plt.imshow(N) #이것도 시각화 이상함 다시 

: 

In [35]:
itos = {i:s for s,i in stoi.items()}
itos

{0: 'a',
 1: 'b',
 2: 'c',
 3: 'd',
 4: 'e',
 5: 'f',
 6: 'g',
 7: 'h',
 8: 'i',
 9: 'j',
 10: 'k',
 11: 'l',
 12: 'm',
 13: 'n',
 14: 'o',
 15: 'p',
 16: 'q',
 17: 'r',
 18: 's',
 19: 't',
 20: 'u',
 21: 'v',
 22: 'w',
 23: 'x',
 24: 'y',
 25: 'z',
 26: '<S>',
 27: '<E>'}

In [13]:
import matplotlib.pyplot as plt
%matplotlib inline

plt.figure(figsize=(16,16))
plt.imshow(N, cmap='Blues')
for i in range(27):
    for j in range(27):
        chstr = itos[i] + itos[j]
        plt.text(j, i, chstr, ha="center", va="bottom", color='gray')
        plt.text(j, i, N[i, j].item(), ha="center", va="top", color='gray')
plt.axis('off');

NameError: name 'itos' is not defined

: 

In [14]:
N[0, :].shape # tensor의 첫번째 행 보기 

torch.Size([28])

In [18]:
p = N[0].float()
p = p/ p.sum() #정규화 
p

tensor([0.0164, 0.0160, 0.0139, 0.0308, 0.0204, 0.0040, 0.0050, 0.0688, 0.0487,
        0.0052, 0.0168, 0.0746, 0.0482, 0.1605, 0.0019, 0.0024, 0.0018, 0.0963,
        0.0330, 0.0203, 0.0112, 0.0246, 0.0048, 0.0054, 0.0605, 0.0128, 0.0000,
        0.1960])

In [27]:
g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3,generator = g ) 
p = p/p.sum()
p

tensor([0.6064, 0.3033, 0.0903])

In [31]:
torch.multinomial(p, num_samples=20, replacement=True, generator=g) #replacement = 복원 추출 

tensor([1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1])

In [38]:
# item사용해서 itos의 값 가져오는 간단한 방법 
g= torch.Generator().manual_seed (2147483647)
ix = torch.multinomial(p, num_samples =1 , replacement =True , generator = g ).item()
itos[ix]

'a'

In [47]:
P = N.float()
P =P /P.sum(1,keepdim=True).shape
P

TypeError: unsupported operand type(s) for /: 'Tensor' and 'torch.Size'

In [42]:
g= torch.Generator().manual_seed (2147483647)

out = []
ix = 0
while True : 
    p = P[ix]
    # p=N[ix].float()
    # p = p/ p.sum()
    p = torch.ones(27)/ 27.0
    ix = torch.multinomial(p, num_samples =1 , replacement =True , generator = g ).item()
    out.append(itox[ix])
    if ix ==0:
        break
print(''.join(out))

RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

In [48]:
0.6926.exp()

AttributeError: 'float' object has no attribute 'exp'